### Handling imbalance dataset
1. up sampling ------> Increase minority class samples.
2. down sampling ----> Decrease majority class samples.

In [1]:
import numpy as np
import pandas as pd

## set the random seed for the reproducibility
np.random.seed(123)

n_sample = 1000

## create the dataframe with two class
n_class_0_ratio = 0.9
n_class_0 = int(n_sample * n_class_0_ratio)
n_class_1 = n_sample - n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [3]:
## Creating the Dataframe with imbalance Dataset

class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0), ## loc = mean, scale=standard divation
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'target' : [1] * n_class_1
})

In [4]:
df = pd.concat([class_0,class_1]).reset_index(drop=True)

In [5]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [6]:
df.sample(5)

     feature_1  feature_2  target
382  -1.305786  -0.366811       0
879   0.997957   1.482163       0
37    0.688223   0.670512       0
98    0.379401   0.470264       0
990   1.063905  -1.080413       1

In [7]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

### UP Sampling

In [8]:
## up sampling -------> increase the minority class for the data imbalanced
from sklearn.utils import resample

In [9]:
df_minority_upsampled = resample(df_minority, replace=True, ## same row can be selected multiple times
                                 n_samples=len(df_majority), random_state=42)

In [10]:
df_minority_upsampled.shape

(900, 3)

In [11]:
df_minority_upsampled.head(5)

     feature_1  feature_2  target
951  -0.874146  -0.156083       1
992   0.196570  -0.602575       1
914  -0.067830   0.998053       1
971   0.272825   1.034197       1
960   0.870056  -0.449515       1

In [12]:
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

In [13]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [14]:
df_upsampled.shape

(1800, 3)

## Down Sampling 
reduced the number of the sample for the 
2. down sampling is bad b/c we lossed the data

In [15]:
## Creating the Dataframe with imbalance Dataset

class_0 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_0), ## loc = mean, scale=standard divation
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'feature_2' : np.random.normal(loc=0, scale=1, size=n_class_1),
    'target' : [1] * n_class_1
})

In [17]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [25]:
from sklearn.utils import resample
df_majority_downsampled = resample(df_majority, replace=False, 
                          n_samples=len(df_minority), random_state=42)

In [27]:
df_majority_downsampled.shape

(100, 3)

In [23]:
print(df_minority.shape)
print(df_majority.shape)
print(df_majority_downsampled.shape)

(100, 3)
(900, 3)
(100, 3)

In [28]:
df_downsampled = pd.concat([df_minority, df_downsampled])

In [29]:
df_downsampled.shape

(200, 3)

In [31]:
# df_downsampled['target'].value_counts()
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64